server:
  tomcat:
    threads:
      max: 10
      min-spare: 10
      max-queue-capacity: 100
    mbeanregistry:
      enabled: true

spring:
  threads:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/payment}
    username: ${USERNAME}
    password: ${PASSWORD}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 30

      connection-timeout: 850
      validation-timeout: 1000
      idle-timeout: 600000
      max-lifetime: 1800000
      keepalive-time: 120000

      register-mbeans: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

toss:
  payment:
    #uri: https://api.tosspayments.com/v1/payments/confirm
    uri: http://10.0.2.253:8080/v1/payments/confirm
    secret: ${TOSS_PAYMENT_SECRET}
    content-type: application/json
    timeout: 2

payment:
  outbox:
    limiter:
      max-result-apply-tasks: 8
    recovery:
      fixed-delay-ms: 30000
      stale-after-seconds: 60
      batch-size: 100

management:
  server:
    port: 8082

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  metrics:
    tags:
      application: payment-backend
    distribution:
      percentiles-histogram:
        http.server.requests: false
