server:
  tomcat:
    threads:
      max: 200
      min-spare: 10
      max-queue-capacity: 100
    mbeanregistry:
      enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/payment}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

toss:
  payment:
    #uri: https://api.tosspayments.com/v1/payments/confirm
    uri: http://180.83.65.140:8080/v1/payments/confirm
    secret: ${TOSS_PAYMENT_SECRET}
    content-type: application/json
    timeout: 60

management:
  server:
    port: 8082

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: payment-backend
    distribution:
      percentiles-histogram:
        http.server.requests: true
